version: "3.8"
services:
  api:
    # image: thomas-oliver/nestjs-dockerized 
    build:
      dockerfile: Dockerfile
      context: .
      # target: development
    # Mount our host Directory to the docker container
    # Mount (.) current directory to the docker container thomas/src/app
    # reflect file changes from host to container
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    restart: unless-stopped
    environment: 
      # - NODE_ENV: development
      # - JWT_SECRET: 1hard_to_guess_secret7890a
      # - PORT: 3000
      - CHOKIDAR_USEPOLLING=true
      # - WATCHPACK_POLLING=true
    ports:
      - 3000:3000
      # debugging port
      - 9229:9229
    # Run in Debug Mode: npm run start:debug --> Don't forget to start your vscode debugger!
    # Run in dev Mode: npm run start:dev
    command: npm run start:dev